server:
  host: 0.0.0.0
  public: 8.154.30.80
  port: 9000

mysql:
  host: 8.154.30.80
  port: 3306
  user: ainexus
  pass: 845924
  database: ai_nexus

redis:
  addr: 8.154.30.80:6379
  password: 845924
  db: 0

ratelimit:
  limitmax: 100
  window: 1m

deduplication:
  lockduration: 5s

grpcclient:
  serveraddress: 8.154.30.80:50002
  defaulttimeout: 10s

rabbitmq:
  host: 8.154.30.80
  port: 5672
  user: murane
  password: 845924
  vhost: /